// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://snpisdcauvbiwkzqfcta.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNucGlzZGNhdXZiaXdrenFmY3RhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg5MDY1MjAsImV4cCI6MjA3NDQ4MjUyMH0.gyyICfK4FYG0f6MeDQx2hPAQRGnPMV3TxZzIHdxJX7Y";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});